AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CRUD API with Lambda and DynamoDB

Resources:
  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ItemsTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: create_item.lambda_handler
      Runtime: python3.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        CreateApi:
          Type: Api
          Properties:
            Path: /items
            Method: post

  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: get_item.lambda_handler
      Runtime: python3.10
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ItemsTable
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: get

  GetAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: get_all_items.lambda_handler
      Runtime: python3.10
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ItemsTable
      Events:
        GetAllApi:
          Type: Api
          Properties:
            Path: /items
            Method: get

  UpdateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: update_item.lambda_handler
      Runtime: python3.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        UpdateApi:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: put

  DeleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: delete_item.lambda_handler
      Runtime: python3.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        DeleteApi:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: delete

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

